name: elearning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  provider: ^6.1.1
  path: ^1.9.0
  path_provider: ^2.1.2
  
  
  # UI & Utilities
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  fl_chart: ^0.68.0
  
  # Media & AI
  video_player: ^2.9.1
  chewie: ^1.8.5
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.2.5
  image_picker: ^1.2.1

  file_picker: ^10.3.10
  youtube_player_iframe: ^5.2.2
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1

  dio: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
